### ISSUE TITLE
Issue when using the script without any argument

### ISSUE THREAD

**Issue by cruxm4n** [elrandar/lol-seeding#1]
Bonjour,
j'ai vue ton outil et souhaiterai l'utilisé 
Quand je lance le programme et bien installé tout les requirements , voila ce que cela me met : 

```
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main(sys.argv)
  File "main.py", line 120, in main
    open_file(argv[1])
IndexError: list index out of range
```

**Comment by elrandar** [comment]
Bonjour, 
Il faut passer en argument au script un fichier csv qui contient les noms des équipes ainsi que les noms des invocateurs. Il doit avoir cette tête :

```
teamname,summoner1,summoner2,summoner3,summoner4,summoner5
Arkham,TheBatmaann,bibaboudidou,Rune Of Darkness,vThetalentsv,Thaave
Blue Lock,Bachira Meguru,Shoei Baro,Blue Lock,Rin Itoshi,Nosfrat
JackeyLove,Hachι,Colike,PlasmaBlade1,Dream00lexxs,TXHiyu
Kostia's Yorozuya-Sama,OUI KOSTIA OUI,Gimlhi,Wyppii,Hymotek,SystemOfADraven
ILLEGITIM NUCLEAR TEAM,mtm94mtm,Le chef DooWap,TheEdge1,VitamineC1603,GigotSavoureux
Les Pandas Cybernetiques,GandalftheChad,magitsab,Silver Rain,FROKBC Vmax,Xamou
EsmEsport,Ttheau,StarKhal,Chef CHAUD4R,FION MACLANUS,TheFirst92120
```

Dis moi si ça fonctionne pour toi.

**Comment by cruxm4n** [comment]
Pareil ^^
